### ISSUE TITLE
Error and Warning message at running display.launch

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/raspimouse_description#7]
![error_message](https://user-images.githubusercontent.com/18494952/75009243-89763900-54bd-11ea-8770-ca65d0f95fc9.png)

```
[WARN] [1582788547.537572]: The 'use_gui' parameter was specified, which is deprecated.  We'll attempt to find and run the GUI, but if this fails you should install the 'joint_state_publisher_gui' package instead and run that.  This backwards compatibility option will be removed in Noetic.
[ERROR] [1582788547.538605]: Could not find the GUI, install the 'joint_state_publisher_gui' package
[ WARN] [1582788547.556383516]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
```

**Comment by Tiryoh** [comment]
Related: https://github.com/ros/joint_state_publisher/pull/31

**Comment by Tiryoh** [comment]
> The 'use_gui' parameter was specified, which is deprecated

については #19 

> Could not find the GUI, install the 'joint_state_publisher_gui' package

については #8

> The 'state_publisher' executable is deprecated.

については #17

で修正します。
